import fs from 'node:fs';
import { parse } from 'yaml';

export interface ModelDef {
  name: string;
  provider: string;
  model?: string;
  context_window?: number;
  safe_prompt_budget?: number;
  reserved_output_budget?: number;
  unlimited?: boolean;
  skills: string[];
}

export interface ModelsConfig {
  models: ModelDef[];
  routing: Record<string, string[]>;
}

export function loadModelsConfig(file: string): ModelsConfig {
  const doc = parse(fs.readFileSync(file, 'utf8')) as {
    models?: Record<string, Omit<ModelDef, 'name'>>;
    routing?: Record<string, string[]>;
  };
  const models: ModelDef[] = Object.entries(doc.models ?? {}).map(([name, def]) => ({
    ...def,
    name,
    skills: def.skills ?? [],
  }));
  return { models, routing: doc.routing ?? {} };
}

/** Crude but honest: ~4 characters per token. */
export function estimateTokens(text: string): number {
  return Math.ceil(text.length / 4);
}

export interface ModelProvider {
  available(model: ModelDef): Promise<boolean>;
  generate(model: ModelDef, prompt: string): Promise<string>;
}

export class OllamaProvider implements ModelProvider {
  constructor(private baseUrl: string) {}

  async available(model: ModelDef): Promise<boolean> {
    try {
      const res = await fetch(`${this.baseUrl}/api/tags`, { signal: AbortSignal.timeout(3000) });
      if (!res.ok) return false;
      const data = (await res.json()) as { models?: { name: string }[] };
      const want = model.model ?? model.name;
      return (data.models ?? []).some((m) => m.name === want || m.name.split(':')[0] === want);
    } catch {
      return false;
    }
  }

  async generate(model: ModelDef, prompt: string): Promise<string> {
    const res = await fetch(`${this.baseUrl}/api/generate`, {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({ model: model.model ?? model.name, prompt, stream: false }),
      signal: AbortSignal.timeout(300_000),
    });
    if (!res.ok) throw new Error(`ollama generate failed: ${res.status} ${await res.text()}`);
    const data = (await res.json()) as { response?: string };
    return data.response ?? '';
  }
}

/**
 * Canned provider used as last-resort routing fallback and in tests.
 * Tests push exact responses onto `queue`; when the queue is empty it
 * returns plausible output keyed off markers in the prompt so --dry-run
 * works offline end to end.
 */
export class MockProvider implements ModelProvider {
  queue: string[] = [];

  async available(): Promise<boolean> {
    return true;
  }

  async generate(_model: ModelDef, prompt: string): Promise<string> {
    if (this.queue.length) return this.queue.shift()!;
    if (prompt.includes('OPTIONS:')) {
      if (prompt.includes('→')) return 'NO_QUESTIONS';
      return [
        'QUESTION: Who is the primary user of this feature?',
        'OPTIONS:',
        'A. The solo operator running the cockpit',
        'B. Future collaborators reviewing runs',
        'C. Automation agents consuming the API',
      ].join('\n');
    }
    if (prompt.includes('JSON array')) {
      return JSON.stringify([
        { title: 'First mock slice', body: 'Mock child issue.\n\n- [ ] acceptance criterion' },
        { title: 'Second mock slice', body: 'Mock child issue.\n\n- [ ] acceptance criterion' },
      ]);
    }
    return '# PRD: Mock feature\n\n## Summary\nGenerated by the mock provider.\n\n## Acceptance criteria\n- It works.';
  }
}

export interface RoutedModel {
  model: ModelDef;
  provider: ModelProvider;
  reason: string;
}

export class ModelRouter {
  constructor(
    private cfg: ModelsConfig,
    private providers: Record<string, ModelProvider>,
  ) {}

  async route(skill: string, estimatedTokens: number): Promise<RoutedModel> {
    const order = this.cfg.routing[skill] ?? this.cfg.models.map((m) => m.name);
    const tried: string[] = [];
    for (const name of order) {
      const model = this.cfg.models.find((m) => m.name === name);
      if (!model) {
        tried.push(`${name}: not defined`);
        continue;
      }
      if (!model.unlimited && model.safe_prompt_budget && estimatedTokens > model.safe_prompt_budget) {
        tried.push(`${name}: over budget (${estimatedTokens} > ${model.safe_prompt_budget})`);
        continue;
      }
      const provider = this.providers[model.provider];
      if (!provider) {
        tried.push(`${name}: no provider "${model.provider}"`);
        continue;
      }
      if (!(await provider.available(model))) {
        tried.push(`${name}: unavailable`);
        continue;
      }
      return { model, provider, reason: `skill=${skill}, ~${estimatedTokens} tokens` };
    }
    throw new Error(`no model available for skill "${skill}" (~${estimatedTokens} tokens). Tried: ${tried.join('; ')}`);
  }
}
