import fs from 'node:fs';
import path from 'node:path';
import { parse } from 'yaml';
import { runCli, type CliRunner } from './cli.js';

export interface ModelDef {
  name: string;
  provider: string;
  model?: string;
  context_window?: number;
  safe_prompt_budget?: number;
  reserved_output_budget?: number;
  unlimited?: boolean;
  skills: string[];
}

export interface ModelsConfig {
  models: ModelDef[];
  routing: Record<string, string[]>;
}

export function loadModelsConfig(file: string): ModelsConfig {
  const doc = parse(fs.readFileSync(file, 'utf8')) as {
    models?: Record<string, Omit<ModelDef, 'name'>>;
    routing?: Record<string, string[]>;
  };
  const models: ModelDef[] = Object.entries(doc.models ?? {}).map(([name, def]) => ({
    ...def,
    name,
    skills: def.skills ?? [],
  }));
  return { models, routing: doc.routing ?? {} };
}

/** Crude but honest: ~4 characters per token. */
export function estimateTokens(text: string): number {
  return Math.ceil(text.length / 4);
}

export interface ModelProvider {
  available(model: ModelDef): Promise<boolean>;
  generate(model: ModelDef, prompt: string): Promise<string>;
}

export class OllamaProvider implements ModelProvider {
  constructor(private baseUrl: string) {}

  async available(model: ModelDef): Promise<boolean> {
    try {
      const res = await fetch(`${this.baseUrl}/api/tags`, { signal: AbortSignal.timeout(3000) });
      if (!res.ok) return false;
      const data = (await res.json()) as { models?: { name: string }[] };
      const want = model.model ?? model.name;
      return (data.models ?? []).some((m) => m.name === want || m.name.split(':')[0] === want);
    } catch {
      return false;
    }
  }

  async generate(model: ModelDef, prompt: string): Promise<string> {
    const res = await fetch(`${this.baseUrl}/api/generate`, {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({ model: model.model ?? model.name, prompt, stream: false }),
      signal: AbortSignal.timeout(300_000),
    });
    if (!res.ok) throw new Error(`ollama generate failed: ${res.status} ${await res.text()}`);
    const data = (await res.json()) as { response?: string };
    return data.response ?? '';
  }
}

/**
 * Canned provider used as last-resort routing fallback and in tests.
 * Tests push exact responses onto `queue`; when the queue is empty it
 * returns plausible output keyed off markers in the prompt so --dry-run
 * works offline end to end.
 */
export class MockProvider implements ModelProvider {
  queue: string[] = [];

  async available(): Promise<boolean> {
    return true;
  }

  async generate(_model: ModelDef, prompt: string): Promise<string> {
    if (this.queue.length) return this.queue.shift()!;
    if (prompt.includes('OPTIONS:')) {
      if (prompt.includes('→')) return 'NO_QUESTIONS';
      return [
        'QUESTION: Who is the primary user of this feature?',
        'OPTIONS:',
        'A. The solo operator running the cockpit',
        'B. Future collaborators reviewing runs',
        'C. Automation agents consuming the API',
      ].join('\n');
    }
    if (prompt.includes('JSON array')) {
      return JSON.stringify([
        { title: 'First mock slice', body: 'Mock child issue.\n\n- [ ] acceptance criterion' },
        { title: 'Second mock slice', body: 'Mock child issue.\n\n- [ ] acceptance criterion' },
      ]);
    }
    return '# PRD: Mock feature\n\n## Summary\nGenerated by the mock provider.\n\n## Acceptance criteria\n- It works.';
  }
}

/** Matches the usage-limit / quota error shapes the subscription CLIs emit. */
export function isQuotaError(text: string): boolean {
  return /usage limit|rate.?limit|quota|hit your limit|limit resets|out of extended usage/i.test(text);
}

/** Parse `claude -p --output-format json` output into the result text. */
export function parseClaudeJson(stdout: string): string {
  let parsed: { result?: unknown; is_error?: boolean; subtype?: string };
  try {
    parsed = JSON.parse(stdout.trim()) as typeof parsed;
  } catch {
    throw new Error(`claude -p returned unparseable output: ${stdout.slice(0, 200)}`);
  }
  if (parsed.is_error || typeof parsed.result !== 'string') {
    throw new Error(`claude -p error: ${String(parsed.result ?? parsed.subtype ?? stdout).slice(0, 400)}`);
  }
  return parsed.result;
}

const QUOTA_COOLDOWN_MS = 15 * 60_000;

/**
 * Subscription-backed text provider via headless Claude Code (`claude -p`).
 * Runs from an empty scratch directory with no tool grants, so it is pure
 * text generation. On usage-limit errors it goes into cooldown and the
 * router falls through to local models.
 */
export class ClaudeCodeProvider implements ModelProvider {
  private unavailableUntil = 0;
  private binaryOk: boolean | null = null;

  constructor(
    private opts: { scratchDir: string; command?: string; run?: CliRunner },
  ) {}

  private get cmd() {
    return this.opts.command ?? 'claude';
  }

  private get run(): CliRunner {
    return this.opts.run ?? runCli;
  }

  async available(): Promise<boolean> {
    if (Date.now() < this.unavailableUntil) return false;
    if (this.binaryOk === null) {
      try {
        this.binaryOk = (await this.run(this.cmd, ['--version'], { timeoutMs: 15_000 })).code === 0;
      } catch {
        this.binaryOk = false;
      }
    }
    return this.binaryOk;
  }

  async generate(model: ModelDef, prompt: string): Promise<string> {
    fs.mkdirSync(this.opts.scratchDir, { recursive: true });
    const args = ['-p', '--output-format', 'json', '--model', model.model ?? 'sonnet'];
    const r = await this.run(this.cmd, args, {
      input: prompt,
      cwd: this.opts.scratchDir,
      timeoutMs: 600_000,
    });
    const combined = r.stdout + r.stderr;
    if (r.code !== 0) {
      if (isQuotaError(combined)) this.unavailableUntil = Date.now() + QUOTA_COOLDOWN_MS;
      throw new Error(`claude -p exited ${r.code}: ${(r.stderr || r.stdout).slice(0, 400)}`);
    }
    try {
      return parseClaudeJson(r.stdout);
    } catch (err) {
      if (isQuotaError(combined)) this.unavailableUntil = Date.now() + QUOTA_COOLDOWN_MS;
      throw err;
    }
  }
}

/**
 * Subscription-backed text provider via OpenAI Codex CLI (`codex exec`).
 * read-only sandbox, scratch cwd, result read from --output-last-message.
 * On Windows the npm-installed `codex` is a .cmd shim, so it runs via cmd /c.
 */
export class CodexCliProvider implements ModelProvider {
  private unavailableUntil = 0;
  private binaryOk: boolean | null = null;

  constructor(
    private opts: { scratchDir: string; command?: string; run?: CliRunner; authPath?: string },
  ) {}

  private get cmd() {
    return this.opts.command ?? 'codex';
  }

  private get run(): CliRunner {
    return this.opts.run ?? runCli;
  }

  private exec(args: string[], input?: string) {
    const opts = { input, cwd: this.opts.scratchDir, timeoutMs: 600_000 };
    return process.platform === 'win32'
      ? this.run('cmd', ['/c', this.cmd, ...args], opts)
      : this.run(this.cmd, args, opts);
  }

  async available(): Promise<boolean> {
    if (Date.now() < this.unavailableUntil) return false;
    if (this.opts.authPath && !fs.existsSync(this.opts.authPath)) return false;
    if (this.binaryOk === null) {
      try {
        fs.mkdirSync(this.opts.scratchDir, { recursive: true });
        this.binaryOk = (await this.exec(['--version'])).code === 0;
      } catch {
        this.binaryOk = false;
      }
    }
    return this.binaryOk;
  }

  async generate(model: ModelDef, prompt: string): Promise<string> {
    fs.mkdirSync(this.opts.scratchDir, { recursive: true });
    const outFile = path.join(this.opts.scratchDir, `codex-${Date.now()}-${Math.random().toString(36).slice(2, 8)}.txt`);
    const args = [
      'exec',
      '--sandbox', 'read-only',
      '--skip-git-repo-check',
      '-C', this.opts.scratchDir,
      '--output-last-message', outFile,
    ];
    if (model.model) args.push('-m', model.model);
    args.push('-'); // read the prompt from stdin
    try {
      const r = await this.exec(args, prompt);
      const combined = r.stdout + r.stderr;
      if (r.code !== 0) {
        if (isQuotaError(combined)) this.unavailableUntil = Date.now() + QUOTA_COOLDOWN_MS;
        throw new Error(`codex exec exited ${r.code}: ${(r.stderr || r.stdout).slice(0, 400)}`);
      }
      if (!fs.existsSync(outFile)) throw new Error('codex exec produced no output message file');
      return fs.readFileSync(outFile, 'utf8');
    } finally {
      try {
        fs.rmSync(outFile, { force: true });
      } catch {
        /* scratch cleanup only */
      }
    }
  }
}

export interface RoutedModel {
  model: ModelDef;
  provider: ModelProvider;
  reason: string;
}

export class ModelRouter {
  constructor(
    private cfg: ModelsConfig,
    private providers: Record<string, ModelProvider>,
  ) {}

  async route(skill: string, estimatedTokens: number): Promise<RoutedModel> {
    const order = this.cfg.routing[skill] ?? this.cfg.models.map((m) => m.name);
    const tried: string[] = [];
    for (const name of order) {
      const model = this.cfg.models.find((m) => m.name === name);
      if (!model) {
        tried.push(`${name}: not defined`);
        continue;
      }
      if (!model.unlimited && model.safe_prompt_budget && estimatedTokens > model.safe_prompt_budget) {
        tried.push(`${name}: over budget (${estimatedTokens} > ${model.safe_prompt_budget})`);
        continue;
      }
      const provider = this.providers[model.provider];
      if (!provider) {
        tried.push(`${name}: no provider "${model.provider}"`);
        continue;
      }
      if (!(await provider.available(model))) {
        tried.push(`${name}: unavailable`);
        continue;
      }
      return { model, provider, reason: `skill=${skill}, ~${estimatedTokens} tokens` };
    }
    throw new Error(`no model available for skill "${skill}" (~${estimatedTokens} tokens). Tried: ${tried.join('; ')}`);
  }
}
